#!/bin/sh
#


function deploy {
  # change the following line to the path of your hooks directory	
  cd ~/documents/test/bare-repo/hooks
  echo "Deploying local GIT work repo"
  # change the following line to point to the deploy.py script
  ~/documents/test/bare-repo/hooks/deploy.py
}

deploy